name: ringsys
channels:
  - openeye
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - chembl_structure_pipeline=1.0.0
  - colorama=0.4.4
  - cycler=0.10.0
  - decorator=5.0.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.0
  - icu=68.1
  - iniconfig=1.1.1
  - intel-openmp=2021.3.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.17.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - mols2grid=0.0.6
  - more-itertools=8.7.0
  - ncurses=6.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openeye-toolkits=2020.2.2
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=20.9
  - pandas=1.2.4
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.1
  - pixman=0.40.0
  - pluggy=0.13.1
  - prompt-toolkit=3.0.17
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycairo=1.20.0
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pytest=6.2.3
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=20.0.0
  - rdkit=2021.03.2
  - readline=8.1
  - reportlab=3.5.67
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlalchemy=1.4.15
  - sqlite=3.35.4
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.62.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - matplotlib-venn==0.11.6
    - seaborn==0.11.2
    - venn==0.1.3
